### PR TITLE
Fix #823: Support virtual coordinate in mozc_renderer to fix its window position on HiDPI displays

### LINKED ISSUE #823: Mozc Renderer: Windows are not placed under the cursor with HiDPI display
## Description
Qt6 does not support AA_EnableHighDpiScaling as mentioned in compiler warnings.

```
renderer/qt/qt_server.cc:109:34: warning: 'Qt::AA_EnableHighDpiScaling' is deprecated: High-DPI scaling is always enabled.
This attribute no longer has any effect. [-Wdeprecated-declarations]
 109 |   QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
```

It now always uses virtual pixels. However, IBus only knows about device pixels and it sends a preedit rect in device pixel coordinates. Thus, a candidate window is usually placed bottom-right of the appropriate place.

## Steps to reproduce
1. Set display DPI to 120
2. Open gEdit, type some keys
3. The suggestion window and candidate window is not shown in a correct place

## Screenshots
Screenshot_20231017_222954

## Version or commit-id
Mozc-2.29.5220.102+24.11.oss

## Environment
 - OS: openSUSE Leap 15.5, 
 - IMF (for Linux): IBus 1.5.25
 - Related Applications
   * Qt 6.4.2
   * KDE Plasma 5.27.4.1-bp155.1.7

## Investigations
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + gEdit, VSCode
 - What applications this issue does not happen on (e.g. Chromium, gedit).
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + list of versions or commit-ids, or no-investigation.

## Additional context

* I cannot find any function that converts device pixels to virtual. We might need to talk with the Qt community.
* Here is Qt-side code that converts virtual to device   
   https://codereview.qt-project.org/c/qt/qtbase/+/451617/2/src/plugins/platforminputcontexts/ibus/qibusplatforminputcontext.cpp
* Workaround: `QT_ENABLE_HIGHDPI_SCALING=0 /usr/lib64/mozc/mozc_renderer`
   * https://doc.qt.io/qt-6/highdpi.html

### PR DESCRIPTION
**Pull request by ftake**
## Description
Qt6 applications use virtual coordinates. Since IBus use the device pixel coordinate system to represent a position of a pre-edit area, mozc_renderer converts it to the virtual coordinate.

## Issue IDs
#823 

## Steps to test new behaviors (if any)
A clear and concise description about how to verify new behaviors (if any).
 - OS: Linux
 - Steps:
   1. Enable display scaling on a desktop environment (e.g. 125%)
   2. Start a GTK application (e.g. gedit)
   3. Type some keys with ibus-mozc enabled and the candidate window is now shown under the cursor.

## Additional context
See #823

### CODE REVIEW

**Comment by hiroyuki-komatsu** [comment]
Hi ftake,
We have been running the internal process to accept your PR.

Thank you for your contribution.

File: src/renderer/qt/qt_window_manager.cc [hunk 1]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
...
 
+struct VirtualRect {
+  const QScreen *screen;
+  const Rect rect;
+
+  VirtualRect(const QScreen *screen, const Rect rect)
+      : screen(screen), rect(rect) {}
+};
+
+Rect TranslateToVirtualRectWithScreen(const QScreen *screen,
```
Comment (yuryu) [inline src/renderer/qt/qt_window_manager.cc:352]: I find the function name a bit confusing because it returns `Rect`, not `VirtualRect`.

File: src/renderer/qt/qt_window_manager.cc [hunk 2]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
...
+  const int vx =
+      (native_rect.Left() - screen_left) / device_pixel_ratio + screen_left;
+  const int vy =
+      (native_rect.Top() - screen_top) / device_pixel_ratio + screen_top;
+
+  return Rect(vx, vy, native_rect.Width() / device_pixel_ratio,
+              native_rect.Height() / device_pixel_ratio);
+}
+
+VirtualRect TranslateToVirtualRect(const Rect &native_rect) {
```
Comment (yuryu) [inline src/renderer/qt/qt_window_manager.cc:368]: optional: I prefer to have this function as a static member of `VirtualRect`, but it's a personal preference.

e.g. `static VirtualRect FromNativeRect(const &native_rect)`

File: src/renderer/qt/qt_window_manager.cc [hunk 3]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
 }
 }  // namespace
 
+struct VirtualRect {
+  const QScreen *screen;
```
Comment (yuryu) [inline src/renderer/qt/qt_window_manager.cc:345]: Please follow https://google.github.io/styleguide/cppguide.html#Declaration_Order

The data members should come last.

File: src/renderer/qt/qt_window_manager.cc [hunk 4]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
...
+  const Rect rect;
```
Comment (yuryu) [inline src/renderer/qt/qt_window_manager.cc:346]: I think this member should be non-const.

Comment (hiroyuki-komatsu) [reply src/renderer/qt/qt_window_manager.cc:346]: Context: https://abseil.io/tips/177

File: src/renderer/qt/qt_window_manager.cc [hunk 5]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
 }
 }  // namespace
 
+struct VirtualRect {
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:344]: optional: How about making it a class and adding `GetRect` and `GetMonitorRect`?

File: src/renderer/qt/qt_window_manager.cc [hunk 6]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
...
+  return VirtualRect(screen, point);
+}
+
 Point QtWindowManager::GetWindowPosition(
     const commands::RendererCommand &command, const Size &win_size) {
-  const Rect preedit_rect = GetRect(command.preedit_rectangle());
-  const Point win_pos = Point(preedit_rect.Left(), preedit_rect.Bottom());
-  const Rect monitor_rect = GetMonitorRect(win_pos.x, win_pos.y);
+  const Rect native_preedit_rect = GetRect(command.preedit_rectangle());
+  const VirtualRect preedit_rect = TranslateToVirtualRect(native_preedit_rect);
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:390]: Would you copy the PR description here as a comment of why we need VirtualRect?

File: src/renderer/qt/qt_window_manager.cc (hunk 3 above)
Comment (yukawa) [inline src/renderer/qt/qt_window_manager.cc:345]: Can’t we simply store two `Rect` values instead of `QScreen *`, whose lifetime is not obvious to future readers?
```
  Rect screen_rect;
  Rect rect;  // perhaps we should use a bit more descriptive name?
```

You should be able to initialize `screen_rect` with `GetRect(screen->geometry())`, and once it’s initialized we do not need `screen` any more.

File: src/renderer/qt/qt_window_manager.cc [hunk 7]
```diff
@@ -341,16 +341,61 @@ void FillCandidates(const commands::Candidates &candidates,
...
+    }
+  }
+
+  // fall back to primary screen
+  // TODO: Return the nearest monitor rect instead.
+  // See GetMonitorRect
+  const QScreen *screen = QGuiApplication::primaryScreen();
+  Rect point = TranslateToVirtualRectWithScreen(screen, native_rect);
+  return VirtualRect(screen, point);
+}
```
Comment (yukawa) [inline src/renderer/qt/qt_window_manager.cc:385]: Let’s move these local utility type / methods into the existing unnamed namespace.

https://google.github.io/styleguide/cppguide.html#Internal_Linkage

**Comment by ftake** [comment]
Thank you for your review comments and I'm sorry to be late. I revised the code.

File: src/renderer/qt/qt_window_manager.cc (hunk 1 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: I removed  VirtualRectWithScreen from the fuction

File: src/renderer/qt/qt_window_manager.cc (hunk 2 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: I made a factory method `FromNativeRect` and moved it to `VirtualRect`

File: src/renderer/qt/qt_window_manager.cc (hunk 4 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: `VirtualRect` is now a class and removed `const`.

File: src/renderer/qt/qt_window_manager.cc (hunk 6 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: I added comments about Qt's virtual coordinate.

File: src/renderer/qt/qt_window_manager.cc (hunk 3 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: VirtualRect now holds `screen_rect`  instead of a QScreen object.

I keep `rect` as is. Maybe we might need to rename `VirtualRect` itself.

File: src/renderer/qt/qt_window_manager.cc (hunk 7 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: I moved `VirtualRect` into the namespace.

File: src/renderer/qt/qt_window_manager.cc [hunk 8]
```diff
@@ -339,13 +339,67 @@ void FillCandidates(const commands::Candidates &candidates,
   const int width = kColumn0Width + max_width1 + max_width2 + kColumn3Width;
   table->resize(width, total_height);
 }
+
+class VirtualRect {
+ public:
+  static VirtualRect FromNativeRect(const Rect &native_rect) {
+    for (const QScreen *screen : QGuiApplication::screens()) {
+      Rect rect = TranslateToVirtual(screen, native_rect);
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:347]: const Rect ?

File: src/renderer/qt/qt_window_manager.cc [hunk 9]
```diff
@@ -339,13 +339,67 @@ void FillCandidates(const commands::Candidates &candidates,
...
+    Rect rect = TranslateToVirtual(screen, native_rect);
+    return VirtualRect(rect, mozc::renderer::GetRect(screen->geometry()));
+  }
+
+  Rect GetRect() const { return rect_; }
+
+  Rect GetMonitorRect() const { return monitor_rect_; }
+
+ private:
+  VirtualRect(Rect rect, Rect monitor_rect)
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:369]: Does `const Rect &` work?

```
VirtualRect(const Rect &rect, const Rect &monitor_rect)

File: src/renderer/qt/qt_window_manager.cc [hunk 10]
```diff
@@ -339,13 +339,67 @@ void FillCandidates(const commands::Candidates &candidates,
...
+      : rect_(rect), monitor_rect_(monitor_rect) {}
+
+  static Rect TranslateToVirtual(const QScreen *screen,
+                                 const Rect &native_rect) {
+    const double device_pixel_ratio = screen->devicePixelRatio();
+    // screen_left, screen_top have the save value in both virtual and native
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:375]: typo: save → same?

File: src/renderer/qt/qt_window_manager.cc [hunk 11]
```diff
@@ -339,13 +339,67 @@ void FillCandidates(const commands::Candidates &candidates,
...
+      if (screen_rect.contains(rect.Left(), rect.Top())) {
+        return VirtualRect(rect, mozc::renderer::GetRect(screen->geometry()));
+      }
+    }
+
+    // fall back to primary screen
+    // TODO: Return the nearest monitor rect instead.
+    // See GetMonitorRect
+    const QScreen *screen = QGuiApplication::primaryScreen();
+    Rect rect = TranslateToVirtual(screen, native_rect);
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:360]: const Rect ?

File: src/renderer/qt/qt_window_manager.cc [hunk 12]
```diff
@@ -339,13 +339,67 @@ void FillCandidates(const commands::Candidates &candidates,
...
+  Rect rect_;
+  Rect monitor_rect_;
+};
 }  // namespace
 
 Point QtWindowManager::GetWindowPosition(
     const commands::RendererCommand &command, const Size &win_size) {
-  const Rect preedit_rect = GetRect(command.preedit_rectangle());
+  const Rect native_preedit_rect = GetRect(command.preedit_rectangle());
+  // Qt6 applications use virtual coodinates. Sicne IBus use the device pixel
```
Comment (hiroyuki-komatsu) [inline src/renderer/qt/qt_window_manager.cc:396]: typo: IBus uses

**Review by hiroyuki-komatsu — COMMENTED** [review]
Thank you for the update!

File: src/renderer/qt/qt_window_manager.cc (hunk 8 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: added const

File: src/renderer/qt/qt_window_manager.cc (hunk 9 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: Yes, it works. Changed them to const Rect &

File: src/renderer/qt/qt_window_manager.cc (hunk 10 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: Fixed it.

File: src/renderer/qt/qt_window_manager.cc (hunk 11 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: Made this const too.

File: src/renderer/qt/qt_window_manager.cc (hunk 12 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: Fixed it.

File: src/renderer/qt/qt_window_manager.cc (hunk 3 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc]: One idea is changing VirtualRect to VirtualPreeditPositions

File: src/renderer/qt/qt_window_manager.cc [hunk 13]
```diff
@@ -339,13 +339,67 @@ void FillCandidates(const commands::Candidates &candidates,
...
+ private:
+  VirtualRect(const Rect &rect, const Rect &monitor_rect)
+      : rect_(rect), monitor_rect_(monitor_rect) {}
+
+  static Rect TranslateToVirtual(const QScreen *screen,
+                                 const Rect &native_rect) {
+    const double device_pixel_ratio = screen->devicePixelRatio();
+    // screen_left, screen_top have the same value in both virtual and native
+    // coordinate
+    const int screen_left = screen->geometry().x();
```
Comment (yukawa) [inline src/renderer/qt/qt_window_manager.cc:377]: I guess negative coordinate is not used in Linux in general, but for completeness I'd suggest using `std::floor` so that this method does the uniform transformation even when a negative coordinate appears.

```
#include <cmath>
```

```
    const int screen_left = screen->geometry().x();
    const int screen_top = screen->geometry().y();
    const int dx = native_rect.Left() - screen_left;
    const int dy = native_rect.Top() - screen_top;
    const int vx = static_cast<int>(std::floor(dx)) + screen_left;
    const int vy = static_cast<int>(std::floor(dy)) + screen_top;
```

If you don't use `std::floor` there, both `0.5` and `-0.5` will be rounded into `0.0`, which does not make sense.

**Review by yukawa — COMMENTED** [review]
LGTM with a minor comment.

File: src/renderer/qt/qt_window_manager.cc (hunk 13 above)
Comment (ftake) [reply src/renderer/qt/qt_window_manager.cc:377]: Thank you. It now uses `floor` to convert.

**Comment by hiroyuki-komatsu** [comment]
We have merged your PR.
Thank you for your contribution!
